"""empty message

Revision ID: 00cddc5b3863
Revises: 2a70f5aecc5b
Create Date: 2023-09-04 13:30:05.667999

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00cddc5b3863"
down_revision = "2a70f5aecc5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preenchimento", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cep", sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column("logradouro", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("número", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("bairro", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("cidade", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("estado", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pais", sa.String(), nullable=True))
        batch_op.drop_column("endereco")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preenchimento", schema=None) as batch_op:
        batch_op.add_column(sa.Column("endereco", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("pais")
        batch_op.drop_column("estado")
        batch_op.drop_column("cidade")
        batch_op.drop_column("bairro")
        batch_op.drop_column("número")
        batch_op.drop_column("logradouro")
        batch_op.drop_column("cep")

    # ### end Alembic commands ###
