"""empty message

Revision ID: 085f23e36fbd
Revises: 80ee804f029f
Create Date: 2023-07-30 12:35:51.365929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085f23e36fbd'
down_revision = '80ee804f029f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preenchido', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.drop_column('preenchido')

    # ### end Alembic commands ###
