"""empty message

Revision ID: 12fd856cd69c
Revises: 085f23e36fbd
Create Date: 2023-07-30 18:13:54.226575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fd856cd69c'
down_revision = '085f23e36fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('vendedor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('vendedor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
