"""empty message

Revision ID: 2b27bcc59f1f
Revises: 
Create Date: 2023-07-29 17:49:50.045850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b27bcc59f1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campanha_id'), ['id'], unique=False)

    op.create_table('canal_da_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canal_da_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canal_da_venda_id'), ['id'], unique=False)

    op.create_table('forma_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forma_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forma_pagamento_id'), ['id'], unique=False)

    op.create_table('origem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('origem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_origem_id'), ['id'], unique=False)

    op.create_table('propostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('sobre', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('propostas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_propostas_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('nome', sa.String(length=25), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('hierarquia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=True),
    sa.Column('nasc', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cadastrado', sa.DateTime(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rg')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_cliente_id'), ['id'], unique=False)

    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endereco_id'), ['id'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criada', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('acessos', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_id'), ['id'], unique=False)

    op.create_table('telefone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=13), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telefone_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telefone_telefone'), ['telefone'], unique=False)

    op.create_table('links_e_props',
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('proposta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], )
    )
    op.create_table('preenchimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proponente', sa.String(length=90), nullable=True),
    sa.Column('responsavel', sa.String(length=90), nullable=True),
    sa.Column('cnpj', sa.String(length=19), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('aporte', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('lote', sa.String(length=13), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preenchimento_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preenchimento_id'))

    op.drop_table('preenchimento')
    op.drop_table('links_e_props')
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telefone_telefone'))
        batch_op.drop_index(batch_op.f('ix_telefone_id'))

    op.drop_table('telefone')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_id'))

    op.drop_table('links')
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endereco_id'))

    op.drop_table('endereco')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_cpf'))

    op.drop_table('cliente')
    op.drop_table('users')
    with op.batch_alter_table('propostas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_propostas_id'))

    op.drop_table('propostas')
    with op.batch_alter_table('origem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_origem_id'))

    op.drop_table('origem')
    with op.batch_alter_table('forma_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forma_pagamento_id'))

    op.drop_table('forma_pagamento')
    with op.batch_alter_table('canal_da_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canal_da_venda_id'))

    op.drop_table('canal_da_venda')
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campanha_id'))

    op.drop_table('campanha')
    # ### end Alembic commands ###
