"""empty message

Revision ID: 2d6123c6d0cb
Revises: 2b27bcc59f1f
Create Date: 2023-07-29 18:41:02.548497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6123c6d0cb'
down_revision = '2b27bcc59f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalhes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('justificativa', sa.String(length=200), nullable=True),
    sa.Column('preenchimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preenchimento_id'], ['preenchimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detalhes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detalhes_id'), ['id'], unique=False)

    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identidade', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('analise', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('objetivos', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('swot', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.drop_column('swot')
        batch_op.drop_column('objetivos')
        batch_op.drop_column('analise')
        batch_op.drop_column('identidade')

    with op.batch_alter_table('detalhes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalhes_id'))

    op.drop_table('detalhes')
    # ### end Alembic commands ###
