"""empty message

Revision ID: 31ecfb4e71cd
Revises: b4243bd16c08
Create Date: 2023-07-27 21:47:57.113862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ecfb4e71cd'
down_revision = 'b4243bd16c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vendedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_vendedor', 'users', ['vendedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_vendedor', type_='foreignkey')
        batch_op.drop_column('vendedor_id')
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
