"""empty message

Revision ID: 37f22231f929
Revises: 825582ccf8cf
Create Date: 2023-09-08 14:53:03.889752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f22231f929'
down_revision = '825582ccf8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ano', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.drop_column('ano')

    # ### end Alembic commands ###
