"""empty message

Revision ID: 454c4774712f
Revises: 9023f9b0ff04
Create Date: 2023-09-06 12:33:29.961076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "454c4774712f"
down_revision = "9023f9b0ff04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etapas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("prop_id", sa.Integer(), nullable=False),
        sa.Column("etapa", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["links.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prop_id"],
            ["propostas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("etapas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_etapas_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("etapas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_etapas_id"))

    op.drop_table("etapas")
    # ### end Alembic commands ###
