"""empty message

Revision ID: 9c9c06c16240
Revises: bced6aa49fca
Create Date: 2023-07-30 03:04:13.576501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9c06c16240'
down_revision = 'bced6aa49fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('futuro', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.drop_column('futuro')

    # ### end Alembic commands ###
