"""empty message

Revision ID: bced6aa49fca
Revises: 2d6123c6d0cb
Create Date: 2023-07-30 03:02:15.291872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bced6aa49fca'
down_revision = '2d6123c6d0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketing', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.drop_column('marketing')

    # ### end Alembic commands ###
