"""empty message

Revision ID: c53dccce2834
Revises: 12fd856cd69c
Create Date: 2023-07-30 21:47:24.105431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53dccce2834'
down_revision = '12fd856cd69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(), nullable=True),
    sa.Column('nome_aws', sa.String(), nullable=True),
    sa.Column('preenchimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preenchimento_id'], ['preenchimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arquivos_id'), ['id'], unique=False)

    with op.batch_alter_table('canal_da_venda', schema=None) as batch_op:
        batch_op.drop_index('ix_canal_da_venda_id')

    op.drop_table('canal_da_venda')
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_index('ix_endereco_id')

    op.drop_table('endereco')
    with op.batch_alter_table('forma_pagamento', schema=None) as batch_op:
        batch_op.drop_index('ix_forma_pagamento_id')

    op.drop_table('forma_pagamento')
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_index('ix_campanha_id')

    op.drop_table('campanha')
    with op.batch_alter_table('origem', schema=None) as batch_op:
        batch_op.drop_index('ix_origem_id')

    op.drop_table('origem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=30), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('origem', schema=None) as batch_op:
        batch_op.create_index('ix_origem_id', ['id'], unique=False)

    op.create_table('campanha',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=30), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.create_index('ix_campanha_id', ['id'], unique=False)

    op.create_table('forma_pagamento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=30), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forma_pagamento', schema=None) as batch_op:
        batch_op.create_index('ix_forma_pagamento_id', ['id'], unique=False)

    op.create_table('endereco',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cep', sa.VARCHAR(length=8), nullable=True),
    sa.Column('uf', sa.VARCHAR(length=2), nullable=True),
    sa.Column('cidade', sa.VARCHAR(), nullable=True),
    sa.Column('bairro', sa.VARCHAR(), nullable=True),
    sa.Column('rua', sa.VARCHAR(), nullable=True),
    sa.Column('numero', sa.INTEGER(), nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.create_index('ix_endereco_id', ['id'], unique=False)

    op.create_table('canal_da_venda',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=30), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canal_da_venda', schema=None) as batch_op:
        batch_op.create_index('ix_canal_da_venda_id', ['id'], unique=False)

    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arquivos_id'))

    op.drop_table('arquivos')
    # ### end Alembic commands ###
