"""empty message

Revision ID: d30fe9a80b71
Revises: 70c23237c701
Create Date: 2023-07-31 03:37:35.690655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30fe9a80b71'
down_revision = '70c23237c701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observações', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preenchimento', schema=None) as batch_op:
        batch_op.drop_column('observações')

    # ### end Alembic commands ###
